- hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Include modular task lists
      ansible.builtin.include_tasks: "{{ item}}"
      loop:
        - tasks/packages.yml
        - tasks/os_configuration.yml
